### ISSUE TITLE
Integer Remap causes crash for non-English DNS users

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#148]

**Comment by synkarius** [comment]
In the settings file `caster/bin/data/settings.json`, find the setting called `integer_remap_crash_fix` and set it to `true`. This should resolve the problem.

**Comment by seekM** [comment]
I can confirm that it does not crash anymore.

**Comment by seekM** [comment]
I just noticed that DNS does not crash if - when starting DNS - I first select my english profile and then switch to my non-englisch profile. If I directly select my non-english profile when starting DNS, it still crashes.

**Comment by synkarius** [comment]
Thank you for confirming that it works now.

That's strange about the language selection order. I don't know what to make of that.

**Comment by seekM** [comment]
As stated in #149, putting `"de": "dragonfly.language.de"` into [`language_map`](https://github.com/t4ngo/dragonfly/blob/94c69ad90f11e21ce2d8d208c85b9ff51ca0eb0e/dragonfly/language/loader.py#L55) avoids crashing if the german profile is loaded. Now language selection order does not matter anymore, too.

**Comment by synkarius** [comment]
Thank you. I've added that to [my Dragonfly repo](https://github.com/synkarius/dragonfly/commit/dd744270e0904943550fd739d8e3f293cd8efe2a) and submitted a pull request to @t4ngo's repo.
